Error Sintáctico en línea 6, columna 4: Esperado 'SIMBOLO', encontrado 'IDENTIFICADOR' (a)
Error Sintáctico en línea 7, columna 6: Se esperaba ')' para cerrar expresión
Error Sintáctico en línea 8, columna 4: Esperado 'SIMBOLO', encontrado 'IDENTIFICADOR' (y)
Error Sintáctico en línea 11, columna 8: Esperado 'SIMBOLO', encontrado 'IDENTIFICADOR' (y)
Error Sintáctico en línea 10, columna 4: Se esperaba ')' después de la condición
Error Sintáctico en línea 32, columna 0: Token inesperado: SIMBOLO (})
Error Sintáctico en línea 32, columna 0: Fin inesperado del archivo
Error Sintáctico en línea 21, columna 4: Se esperaba 'end' para cerrar if
Error Sintáctico en línea 32, columna 0: Fin inesperado del archivo
Error Sintáctico en línea 1, columna 0: Se esperaba '}' para cerrar main
